### ISSUE TITLE
How to take screenshots

### ISSUE THREAD

**Issue by cmatte** [jeroenterheerdt/ring-hassio#19]
Hi There,

Thanks for the 1.3 update! Fixes the previous issue 👍 

Can you help with more details on how to take screenshots?

Attempting to use the following creates a .m3u8 file into the .jpg file:
```
service: camera.snapshot
entity_id: [entityID]
filename: tmp/foo.jpg

```

foo.jpg:
```
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-TARGETDURATION:2
#EXT-X-MEDIA-SEQUENCE:28
#EXTINF:2.000000,
stream28.ts
#EXTINF:2.000000,
stream29.ts
#EXTINF:2.000000,
stream30.ts
#EXTINF:2.000000,
stream31.ts
#EXTINF:2.000000,
stream32.ts
#EXTINF:2.000000,
stream33.ts
```

I am trying to mainly use the add-on to take screenshots and notify my devices of any rings, so this is key :) 

Thank you!

**Comment by jeroenterheerdt** [comment]
As noted here (https://github.com/jeroenterheerdt/ring-hassio#taking-a-snapshot) you cannot take a screenshot at the moment.

**Comment by Alexwijn** [comment]
Sure, you can.

```
camera:
  - platform: ffmpeg
    input: http://hassio.local:port/public/stream.m3u8
```

Just make sure you have the [`ffmpeg`](https://www.home-assistant.io/integrations/ffmpeg/) integration installed.
