### ISSUE TITLE
Livestream is not working

### ISSUE THREAD

**Issue by rafalkarwecki** [jeroenterheerdt/ring-hassio#23]
I installed everything according to the instructions on raspberry pi 4. I generated a token. I have defined a new camera as well. The broadcast transmission window starts but the broadcast is not available.

@CURL:
> curl -i 'http://local:3000/public/stream.m3u8'
> HTTP/1.1 200 OK
> Content-Type: application/vnd.apple.mpegurl
> Date: Wed, 26 Aug 2020 16:49:27 GMT
> Connection: keep-alive
> Transfer-Encoding: chunked
> 
> #EXTM3U
> #EXT-X-VERSION:3
> #EXT-X-TARGETDURATION:2
> #EXT-X-MEDIA-SEQUENCE:17
> #EXTINF:1.920000,
> stream17.ts
> #EXTINF:2.048000,
> stream18.ts
> #EXTINF:1.920000,
> stream19.ts
> #EXTINF:1.920000,
> stream20.ts
> #EXTINF:1.920000,
> stream21.ts
> #EXTINF:1.920000,
vstream22.ts

@Logs:
> [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
> [s6-init] ensuring user provided files have correct perms...exited 0.
> [fix-attrs.d] applying ownership & permissions fixes...
> [fix-attrs.d] done.
> [cont-init.d] executing container initialization scripts...
> [cont-init.d] done.
> [services.d] starting services
> [services.d] done.
> output directory: public/
> Started server, listening on port 3000.
> **socket 0 opened**
> requested uri: /public/stream.m3u8
> mapped filename: public/stream.m3u8
> sending file: public/stream.m3u8
> **socket 0 closed**
> Call has ended
> Restarting server
> Server closed!
> output directory: public/
> Started server, listening on port 3000.

Unfortunately stream is not available in home assistant and vlc as well.

**Comment by lensherm** [comment]
Similar results here

**Comment by Russell-Morgan** [comment]
getting the same problem

**Comment by Jens-Wymeersch** [comment]
Same here. I can't make the live stream work !

**Comment by Toggz** [comment]
Same issue with me. Worked for a little while on HA (10 second clips however) next day blank video. :(

**Comment by Jens-Wymeersch** [comment]
In ring, I've noticed it opens a live session but I can't see in the browser. Ideally we should have the ability to open a live session and maybe for the rest every 10 min - 5 second views.

**Comment by pdrittenhouse** [comment]
Watching.  Same issue here.

**Comment by totalitarian** [comment]
Same issue here. Worked yesterday - now can't get it to work

**Comment by Brahmah** [comment]
[This pull](https://github.com/jeroenterheerdt/ring-hassio/pull/27) should remedy this!

Ring made a minor amendment to their API which was considered in the latest version of the ring client library used here. The pull upgrades said library to the latest version.
