### ISSUE TITLE
 ring doorbell does not communicate

### ISSUE THREAD

**Issue by pollinolas** [jeroenterheerdt/ring-hassio#29]
Hello, I have noticed that when I turn on the addon, the ring doorbell device does not communicate when someone presses the doorbell, I mean that at the HA level and in the ring app there is no notification of any kind until a few minutes have passed.
Sorry for my English, the google translator is helping me.

**Comment by jeroenterheerdt** [comment]
@pollinolas that is an effect of running the livestream continuously. that's why we need a way to start/stop the add-on

**Comment by pollinolas** [comment]
Thanks for answering, maybe, these days I have been doing some tests and I have had the addon on continuously. by the way I also confirm that adding the camera as ffmpeg allows you to capture. Greetings.

**Comment by jeroenterheerdt** [comment]
thanks, can you share what your configuration.yaml looks like and what service you call to do the snapshot, because it does not seem to work for everyone.

**Comment by pollinolas** [comment]
camera:
  - platform: ffmpeg
    name: Ring
    input: http://192.168.1.2:3000/public/stream.m3u8

the service that  I use is the camera.snapshot with a delay before and a smaller one after
  - delay: 00:00:10
  - data:
      entity_id: camera.ring
      filename: '/config/www/camaras/videoportero.jpg'
    service: camera.snapshot
  - delay: 00:00:03
