### ISSUE TITLE
Error installing this addon

### ISSUE THREAD

**Issue by mahoekst** [jeroenterheerdt/ring-hassio#3]
Not sure why it doesn't want to install? (HassOS 3.8)
20-02-08 04:37:12 INFO (SyncWorker_10) [hassio.docker.addon] Start build d4b7a20a/armv7-addon-ringlivestream:0.0.2
20-02-08 04:37:21 ERROR (SyncWorker_10) [hassio.docker.addon] Can't build d4b7a20a/armv7-addon-ringlivestream:0.0.2: The command '/bin/bash -o pipefail -c apk add --no-cache     nodejs=12.14.0-r0     npm=12.14.0-r0     ffmpeg     git &&     cd / &&     git clone https://github.com/jeroenterheerdt/ring-hassio &&     cd ring-hassio/ring_hassio &&     npm install --unsafe-perm &&     chmod a+x run.sh' returned a non-zero code: 2

**Comment by jeroenterheerdt** [comment]
I think there is something going on with the updated ring-api package. I will take a look

**Comment by jeroenterheerdt** [comment]
found an issue, can you refresh the repos in HASSIO and try again?

**Comment by mahoekst** [comment]
when you say refresh the repos, how do I do that? If I go to the addon it says version 0.2 and doesn't install.
I removed the repo and added it again and tried to install again, now it installed successfully :)

**Comment by jeroenterheerdt** [comment]
For what it's worth: there is a refresh button at the top. I forgot to update the version number, otherwise you should have been able to just update the addon (I think).

**Comment by mahoekst** [comment]
Oh crap, MFA is switched on
