### ISSUE TITLE
hass.io on Synology DSM - docker does not start

### ISSUE THREAD

**Issue by cmatte** [jeroenterheerdt/ring-hassio#7]
Hi @jeroenterheerdt 
This docker seems all setup as per the instructions, however at start it throws the following and exits. I have failed to run this in the manual mode also, unfortunately.

I am testing this on a Synology DSM DS918+ - this might be the reason...but you can feel how close you are...ideas?

```
ifelse: fatal: unable to exec /ring-hassio/ring_hassio/run.sh: Exec format error | stderr
[cmd] /ring-hassio/ring_hassio/run.sh exited 126 | stdout
[cont-finish.d] executing container finish scripts... | stdout
[cont-finish.d] done. | stdout
[s6-finish] waiting for services. | stdout
[s6-finish] sending all processes the TERM signal.
```

**Comment by Harryjholmes** [comment]
Noted issue in #5
